import asyncio
import os
import time
import argparse
import sys
from datetime import datetime
from playwright.async_api import async_playwright

# Configuration
WATCH_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Needs_Action")
USER_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "linkedin_user_data")

async def monitor_linkedin():
    print("[LINKEDIN] Starting LinkedIn Watcher...")
    async with async_playwright() as p:
        # Launch browser with persistent context
        browser = await p.chromium.launch_persistent_context(
            user_data_dir=USER_DATA_DIR,
            headless=False,
        )
        
        page = await browser.new_page()
        await page.goto("https://www.linkedin.com/messaging/")
        
        print("[LINKEDIN] Please log in if needed.")
        try:
            await page.wait_for_selector(".msg-conversation-listitem", timeout=60000) # Wait for message list
            print("[LINKEDIN] Messaging interface detected.")
        except:
            print("[LINKEDIN] Timeout waiting for messaging interface.")
            return

        print("[LINKEDIN] Monitoring for new messages...")
        
        processed_messages = set()
        
        while True:
            try:
                # Check for unread indicators
                unread_conversations = await page.query_selector_all(".msg-conversation-card__unread-count")
                
                if unread_conversations:
                    for badge in unread_conversations:
                        # Click conversation
                        card = await badge.xpath("./../../..")
                        if card:
                            await card[0].click()
                            await asyncio.sleep(2)
                            
                            # Extract last message
                            msgs = await page.query_selector_all(".msg-s-event-listitem__body")
                            if msgs:
                                last_msg_el = msgs[-1]
                                text = await last_msg_el.innerText()
                                
                                # Simple duplicate check
                                if text not in processed_messages:
                                    print(f"[LINKEDIN] New message: {text[:50]}...")
                                    processed_messages.add(text)
                                    save_to_needs_action(text)
                                    
                await asyncio.sleep(10)
                
            except Exception as e:
                print(f"[LINKEDIN] Error: {e}")
                await asyncio.sleep(10)

def save_to_needs_action(text):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_linkedin.md"
    filepath = os.path.join(WATCH_FOLDER, filename)
    
    content = f"""---
type: linkedin
received: "{datetime.now().isoformat()}"
status: pending
---

## LinkedIn Message

**Content:**
{text}

---
*Processed by LinkedIn Watcher*
"""
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"[LINKEDIN] Saved task: {filename}")

def simulate_opportunity_event():
    """Simulates a business event for testing."""
    text = "New Silver Tier AI capabilities launched! Check it out."
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_linkedin_opportunity.md"
    filepath = os.path.join(WATCH_FOLDER, filename)
    
    content = f"""---
type: linkedin_opportunity
received: "{datetime.now().isoformat()}"
status: pending
---

## Business Opportunity Detected

**Event:** New Product Launch
**Suggested Action:** Create a LinkedIn post announcing the Silver Tier.

**Context:**
{text}

---
*Generated by LinkedIn Watcher Simulation*
"""
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"[LINKEDIN] Simulated opportunity: {filename}")

async def post_update(content):
    print(f"[LINKEDIN] Starting LinkedIn Poster... Content: {content[:30]}...")
    async with async_playwright() as p:
        # Launch browser with persistent context
        browser = await p.chromium.launch_persistent_context(
            user_data_dir=USER_DATA_DIR,
            headless=False,
        )
        
        page = await browser.new_page()
        
        try:
            await page.goto("https://www.linkedin.com/feed/")
            
            # Check login
            try:
                await page.wait_for_selector('.share-box-feed-entry__trigger, button.share-box-feed-entry__trigger', timeout=10000)
                print("[LINKEDIN] Login verified.")
            except:
                print("[LINKEDIN] Not logged in. Please run monitor mode to login first.")
                return

            # Click "Start a post"
            await page.click('.share-box-feed-entry__trigger, button.share-box-feed-entry__trigger')
            print("[LINKEDIN] Opened post modal.")
            
            # Wait for editor
            editor_selector = '.ql-editor, .share-creation-state__text-editor .ql-editor'
            await page.wait_for_selector(editor_selector)
            
            # Type content
            await page.fill(editor_selector, content)
            print("[LINKEDIN] Content typed.")
            
            await asyncio.sleep(2) # Wait for previews

            # Click Post
            post_button_selector = 'button.share-actions__primary-action'
            post_button = await page.query_selector(post_button_selector)
            
            if post_button:
                is_disabled = await post_button.is_disabled()
                if not is_disabled:
                    # UNCOMMENT TO ACTUALLY POST
                    # await post_button.click()
                    print("[LINKEDIN] (SIMULATION) Clicked Post button.") 
                    print("[LINKEDIN] Success! Post would be live.")
                else:
                    print("[LINKEDIN] Post button is disabled. Content might be empty?")
            else:
                print("[LINKEDIN] Post button not found.")

            await asyncio.sleep(3)

        except Exception as e:
            print(f"[LINKEDIN] Error posting: {e}")

if __name__ == "__main__":
    if not os.path.exists(WATCH_FOLDER):
        os.makedirs(WATCH_FOLDER)
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--simulate", action="store_true", help="Simulate an opportunity event")
    parser.add_argument("--post", help="Post content to LinkedIn")
    args = parser.parse_args()

    if args.simulate:
        simulate_opportunity_event()
    elif args.post:
        try:
            asyncio.run(post_update(args.post))
        except Exception as e:
            print(f"[LINKEDIN] Error: {e}")
    else:
        try:
            asyncio.run(monitor_linkedin())
        except KeyboardInterrupt:
            print("[LINKEDIN] Stopped.")
